config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, only: :sessions, controllers: { sessions: "sessions" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    # When user authenticated, root page is as normal
    authenticated :user do
      root 'projects#dashboard', as: :authenticated_root
    end

    # When no authenticated user, root page is the sign in page
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get '/about', to: 'sessions#about'
    end
  end

  # About page
  get '/about', to: 'sessions#about'

  # Projects
  get '/dashboard', to: 'projects#dashboard'
  get '/costs-breakdown', to: 'projects#costs_breakdown'
  get '/billing-overview', to: 'projects#billing_overview'
  get '/policies', to: 'projects#policy_page'
  get '/audit', to: 'projects#audit'
  get '/json/data-check', to: 'projects#data_check'
  get '/json/audit-logs', to: 'projects#audit_logs'
  post '/config-update', to: 'projects#config_update'

  # Events (change requests and their resulting actions)
  get '/events', to: 'change_requests#manage'
  get '/events/new', to: 'change_requests#new'
  get '/events/:id/edit', to: 'change_requests#edit', as: :event_edit
  get '/json/events/latest', to: 'change_requests#latest'
  get '/json/events/costs-forecast', to: 'change_requests#costs_forecast'
  post '/events/', to: 'change_requests#create'
  post '/events/:id/cancel', to: 'change_requests#cancel'
  post '/events/:id/update', to: 'change_requests#update'
  post '/dashboard/:id/cancel', to: 'change_requests#cancel'

  authenticate :user, lambda {|u| u.admin? } do
    mount Resque::Server.new, :at => "/resque"
  end
end

app/models/change_request.rb
include ActionView::Helpers::SanitizeHelper

class ChangeRequest < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_many :action_logs
  has_many :change_request_audit_logs
  before_save :clean_description
  validates :project_id, :user_id, :counts, :date, :counts_criteria, :time, :status, :type, presence: true
  validate :time_in_future, if: Proc.new { |s| !s.persisted? || s.time_or_date_changed? }
  validate :only_one_at_time, if: Proc.new { |s| !s.persisted? || s.time_or_date_changed? }
  validate :includes_counts, if: Proc.new { |s| !s.persisted? || s.counts_changed? }
  validate :not_over_budget, if: Proc.new { |s| !s.persisted? || s.counts_changed? || s.time_or_date_changed? }

  def nodes=(nodes)
    @nodes = nodes
    update_counts
  end

  after_initialize do |change_request|
    change_request.counts ||= formatted_counts
    change_request.status ||= "pending"
  end

  def update_counts
    self.counts = formatted_counts
  end

  def date_time
    Time.zone.parse("#{date.to_s} #{time}")
  end

  def uneditable_date_time
    (date_time - 5.minutes).to_f * 1000
  end

  def actual_or_parent_id
    self.id
  end

  def customer_facing(type)
    InstanceMapping.customer_facing_type(project.platform, type)
  end

  def monitor_end_time
    monitor_override_hours ? date_time + monitor_override_hours.hours : nil
  end

  def formatted_changes(with_opening=true)
    message = ""
    opening = "#{user.username} requested the following scheduled #{counts_criteria} counts for *#{self.project.name}*:\n"
    counts.each do |group, details|
      message << "*#{group}*\n"
      details.each { |instance, count| message << "#{instance}: #{count} node#{"s" if count > 1 || count == 0}\n" }
    end
    message << "\n*Scheduled time*: #{date_time}\n"
    message << additional_field_details(true)
    message = opening << message if with_opening
    message
  end

  def formatted_actions
    message = ""
    changed = false
    actual_counts = project.actual_with_pending_counts
    counts.each do |group, nodes|
      group_message = "*#{group}*\n"
      group_changed = false
      nodes.each do |instance, count|
        actual_count = actual_counts[group][instance]
        diff = count - actual_count
        if diff > 0
          group_changed = true
          changed = true
          group_message << "#{instance}: turn on #{diff} node#{"s" if diff > 1}\n"
        elsif diff < 0 && counts_criteria == "exact"
          group_changed = true
          changed = true
          group_message << "#{instance}: turn off #{diff.abs} node#{"s" if diff.abs > 1}\n"
        end
      end
      message << group_message if group_changed
    end
    if changed
      message = "Changes submitted for automated actioning as part of a scheduled request for *#{project.name}*\n\n" << message
    else
      message = "No changes required to meet #{counts_criteria} counts in the scheduled request at #{date_time} for *#{project.name}*\n"
    end
    message
  end

  def card_description
    html = "Requested the following:<br><br>"
    html << "<div class='change-details'>"
    counts.each do |group, details|
      html << "<strong>#{group}</strong><br>"
      details.each { |instance, count| html << "#{customer_facing(instance)}: #{count} node#{"s" if count > 1 || count == 0}<br>" }
    end
    html << "<br><strong>Start time</strong>: #{date_time}<br>"
    html << additional_field_details
    html << "</div>"
    html
  end

  def additional_field_details(slack=false)
    additional = ""
    if description
      if slack
        additional << "*Description*: #{description}\n"
      else
        additional << "<strong>Description</strong>: #{description}<br>"
      end
    end
    if monitor_override_hours
      if slack
        additional << "*Override CPU monitor for*: #{monitor_override_hours} hour#{'s' if monitor_override_hours > 1}\n"
      else
        additional << "<strong>Override CPU monitor for</strong>: #{monitor_override_hours} hour#{'s' if monitor_override_hours > 1}<br>"
      end
    end
    additional
  end

  def formatted_days
    nil
  end

  def partial
    'change_request_card'
  end

  def description_partial
    'change_request_event_details'
  end

  def auto_description
    "Match #{counts_criteria == 'min' ? 'minimum' : 'exact'} counts"
  end

  def includes_instance_type?(group, instance_type)
    counts[group][instance_type]
  end

  # Includes counts for any of the provided groups
  def included_in_groups?(groups)
    groups.detect { |group| includes_group?(group) }
  end

  def includes_group?(group)
    counts[group] && !counts[group].blank?
  end

  def instances_to_change_with_pending
    actions = {on: [], off: []}
    project_logs = project.latest_instance_logs
    counts.each do |group, nodes|
      nodes.each do |instance, count|
        instance_logs = project_logs.where(instance_type: instance, compute_group: group)
        on_instances = instance_logs.select { |instance| instance.pending_on? }
        diff = count - on_instances.count
        if diff > 0
          off_instances = instance_logs.select { |instance| !instance.pending_on? }
          instances = off_instances.first(diff.abs)
          actions[:on] = actions[:on].concat(instances)
        elsif diff < 0 && counts_criteria == "exact"
          instances = on_instances.first(diff.abs)
          actions[:off] = actions[:off].concat(instances)
        end
      end
    end
    actions
  end

  def check_and_update_status
    if !@checked
      @checked = true
      return if status != "started"

      action_logs.reorder("actioned_at DESC").each do |log|
        log.check_and_update_status
        return if log.status == "pending"
      end
      complete
    end
  end

  def start
    self.status = "started"
    save!
  end

  def complete
    self.status = "completed"
    save!
  end

  def cancel
    if cancellable?
      self.status = "cancelled"
      save!
    end
  end

  def as_original
    copy = ChangeRequest.new(self.attributes)
    change_request_audit_logs.reorder("created_at DESC").each do |change|
      copy.assign_attributes(change.original_attributes)
    end
    copy.becomes(copy.type.constantize)
  end

  # When we have change logs, we will want to show the original content,
  # but the current status
   def as_json(options={original: true})
    request = options[:original] ? as_original : self
    {
      type: "change_request",
      username: request.user.username,
      date: request.date,
      time: request.time,
      timestamp: request.created_at,
      formatted_timestamp: request.formatted_timestamp,
      details: request.card_description,
      descriptive_counts: descriptive_counts,
      status: status,
      editable: editable?,
      cancellable: cancellable?,
      counts_criteria: counts_criteria.capitalize,
      frontend_id: front_end_id,
      description: description,
      monitor_override_hours: monitor_override_hours,
      link: link,
      updated_at: updated_at.to_s
    }
  end

  def to_json(*options)
    as_json(*options).to_json(*options)
  end

  def front_end_id
    "#{id}-#{date}"
  end

  def time_or_date_changed?
    time_changed? || date_changed?
  end

  def editable?
    status == "pending" && date_time >= (Time.current + 5.minutes)
  end

  def cancellable?
    status == "pending"
  end

  def link
    "/events/#{self.id}/edit?project=#{self.project.name}"
  end

  def switch_all_on?(group_name)
    project_instances = project.latest_instances[group_name]
    return false if counts[group_name].length != project_instances.length

    request_counts = counts[group_name]
    missing = project_instances.detect { |instance| request_counts[instance.instance_type] != instance.total_count }
    !missing
  end

  def switch_all_off?(group_name)
    project_instances = project.latest_instances[group_name]
    request_counts = counts[group_name]
    request_counts.length == project_instances.length &&
    request_counts.values.all?(0)
  end

  def descriptive_counts
    results = {}
    counts.each do |group, instance_types|
      if switch_all_on?(group)
        results[group] = "All on"
      elsif switch_all_off?(group)
        results[group] = "All off"
      else
        customer_facing_types = instance_types.map do |k,v|
          [InstanceMapping.customer_facing_type(project.platform, k),v]
        end.to_h
        results[group] = customer_facing_types
      end
    end
    results
  end

  private

  def formatted_counts
    instances = {}
    return instances if !@nodes

    @nodes.each do |id, count|
      if count != ""
        group = id.split("-")[0]
        type = id.split("-")[1]
        if instances.has_key?(group)
          instances[group][type] = count.to_i
        else
          instances[group] = {type => count.to_i}
        end
      end
    end
    instances
  end

  def clean_description
    if description
      self.description = strip_tags(description)
    end
  end

  def includes_counts
    errors.add(:counts, "must include at least one node count") if counts.empty?
  end

  def time_in_future
    errors.add(:time, " must be at least 5 mins in the future") if (date_time - 5.minutes) < Time.current
  end

  def only_one_at_time
    dates = future_dates
    self.project.change_requests.where(time: self.time).where.not(id: self.id).where.not(status: "cancelled").each do |request|
      if (request.future_dates & dates).any?
        errors.add(:time, "must not be the same as an existing request with actions on the same date")
        return  
      end  
    end
  end

  def not_over_budget
     errors.add(:counts, "must not result in going over budget") if project.change_request_goes_over_budget?(self)
  end
end

app/controllers/change_requests_controller.rb
class ChangeRequestsController < ApplicationController
  def manage
    get_project
    authorize ChangeRequest.new(project: @project)
    @compute_groups = @project.front_end_compute_groups.keys
    @filtered_groups = params[:groups]
    @current_instances = @project.latest_instances
    @in_progress = @project.pending_action_logs
    if @filtered_groups
      @in_progress = @in_progress.select { |log| @filtered_groups.include?(log.compute_group) }
    end
    @upcoming = @project.upcoming_events_by_date(@filtered_groups)
    @future_events = @project.future_events_by_date(@filtered_groups, false)
    filter_records if @filtered_groups
    @nav_view = "manage events"
    @editor = ChangeRequestPolicy.new(current_user, ChangeRequest.new(project: @project)).create?
    check_missing_instance_details
  end

  def latest
    get_project
    authorize ChangeRequest.new(project: @project)
    render json: @project.current_events_data(params[:groups]).to_json({original: false})
  end

  def new
    get_project
    authorize ChangeRequest.new(project: @project)
    @current_instances = @project.latest_instances
    cost_plotter = CostsPlotter.new(@project)
    start_date = cost_plotter.start_of_billing_interval(Date.current)
    end_date = cost_plotter.end_of_billing_interval(start_date)
    @cycle_thresholds = cost_plotter.cycle_thresholds(start_date, end_date)
    @existing_timings = @project.request_dates_and_times
    @nav_view = "event wizard"
    check_missing_instance_details
  end

  def edit
    get_project
    @change_request = ChangeRequest.find_by_id(params[:id])
    unless @change_request
      flash[:danger] = "Request not found"
    else
      authorize @change_request, policy_class: ChangeRequestPolicy
      unless @change_request.editable?
        flash[:danger] = "Cannot edit that request"
        redirect_to request.referrer
        return
      end
    end
    @current_instances = @project.latest_instances
    cost_plotter = CostsPlotter.new(@project)
    start_date = cost_plotter.start_of_billing_interval(Date.current)
    end_date = cost_plotter.end_of_billing_interval(Date.current)
    @cycle_thresholds = cost_plotter.cycle_thresholds(start_date, end_date)
    @existing_timings = @project.request_dates_and_times(@change_request)
    @nav_view = "event wizard"
    check_missing_instance_details
    render :new
  end

  def create
    parameters = filtered_change_request_params
    @project = Project.find_by_name(parameters[:project])
    if !@project
      flash[:danger] = "Project not found"
    else
      authorize ChangeRequest.new(project: @project)
      parameters.delete(:project)
      parameters[:user_id] = current_user.id
      parameters[:over_budget_switch_offs] = parameters[:over_budget_switch_offs] == "true"
      request = @project.create_change_request(parameters)
      if request.valid?
        flash[:success] = "Request created"
      else
        flash[:danger] = format_errors(request)
      end
    end
    redirect_to events_path(project: @project.name)
  end

  def update
    get_project
    parameters = filtered_change_request_params
    request = ChangeRequest.find_by_id(params[:id])
    if !request
      flash[:danger] = "Request not found"
    else
      authorize request, policy_class: ChangeRequestPolicy
      if request.id != parameters[:id].to_i
        flash[:danger] = "Ids do not match"
      else
        if !request.editable?
          flash[:danger] = "Cannot edit that request"
        else
          if parameters["timeframe"] == "now"
            parameters["date"] = Date.current
            # use 6 minutes as equivalent to rounding up current time
            # to nearest minute
            parameters["time"] = (Time.current + 6.minutes).strftime("%H:%M")
          end
          parameters.delete(:project)
          parameters.delete(:timeframe)
          parameters[:over_budget_switch_offs] = parameters[:over_budget_switch_offs] == "true"
          request, success = @project.update_change_request(request, current_user, parameters)
          if success
            flash[:success] = "Request updated"
          else
            if !request.changed?
              flash[:danger] = "No changes made"
            elsif !request.valid?
              flash[:danger] = format_errors(request)
            end
          end
        end
      end
    end
    redirect_to events_path(project: @project.name)
  end

  def cancel
    get_project
    change_request = ChangeRequest.find_by_id(params[:id])
    if !change_request
      flash[:danger] = "Request not found"
    else
      authorize change_request, policy_class: ChangeRequestPolicy
      success = @project.cancel_change_request(change_request, current_user)
      if success
        flash[:success] = "Request cancelled"
      else
        flash[:danger] = "Unable to cancel request"
      end
    end
    redirect_to request.referrer
  end

  def costs_forecast
    parameters = filtered_change_request_params
    @project = Project.find_by_name(parameters[:project])
    authorize ChangeRequest.new(project: @project)
    render json: @project.change_request_cumulative_costs(parameters)
  end

  def filtered_change_request_params
    permitted = params.permit(
      :counts_criteria,
      :project,
      :id,
      :timeframe,
      :date,
      :time,
      :weekdays,
      :type,
      :end_date,
      :description,
      :monitor_override_hours,
      :over_budget_switch_offs,
      nodes: {}
    )
    permitted.transform_values do |value|
      # filter hash within params
      if value.class == ActionController::Parameters
        value.select { |k, v| v != "" }
      else
        value == "" ? nil : value
      end
    end
  end

  def filter_records
    return if !@filtered_groups
    filter_current_instances
    @in_progress.to_a.select! { |log| @filtered_groups.include?(log.compute_group) }
  end

  def filter_current_instances
    original = @current_instances.clone
    @current_instances = original.select { |group, instances| @filtered_groups.include?(group) }
    @current_instances = original if @current_instances.empty?
  end
end

app/views/change_requests/_budget_switch_off_details_card.erb
<div class="card event-details-card budget-switch-off-details-card rounded-0 <%= 'border-bottom-0' if locals[:bottom_border] %>">
  <div class="event-details-column event-details-text budget-switch-off-text">
    <p>
      This is an automated switch off event that has been scheduled to ensure that the budget
      is not overrun.
    </p>
    <p>
      Based on current levels of usage, costs were forecasted to exceed the budget.
      This event will be automatically cancelled if usage levels change and forecasted
      costs are reduced to be within budget.
    </p>
  </div>
</div>

app/views/change_requests/_choose_counts.erb
<div id="wizard-choose-counts" class="wizard-section">
  <div class="wizard-title">
    <h4>What would you like to do?</h4>
  </div>
  <div class="row text-center select-count-type">
    <div class="col-6">
      <div class="form-check">
        <input class="form-check-input"
               type="radio"
               name="counts_criteria"
               id="exact-counts"
               value="exact"
               <%= 'checked' if !@change_request || @change_request.counts_criteria == "exact" %> >
        <label class="form-check-label" for="exact-counts">
          Set exact instance counts<a href="#" class="tool-tip" data-placement="top" title="Instances will be switched on and/or off as needed to match the exact chosen counts."><sup>?</sup></a>
        </label>
      </div>
    </div>
    <div class="col-6">
      <div class="form-check">
        <input class="form-check-input"
               type="radio"
               name="counts_criteria"
               id="min-counts"
               value="min"
               <%= 'checked' if @change_request && @change_request.counts_criteria == "min" %> >
        <label class="form-check-label" for="min-counts">
          Set minimum instance counts<a href="#" class="tool-tip" data-placement="top" title="Instances will be switched on (but not off) as needed to reach the chosen counts."><sup>?</sup></a>
        </label>
      </div>
    </div>
  </div>
  <%= render '/change_requests/node_choices' %>
</div>

app/views/change_requests/_choose_extras.erb
<div id="wizard-choose-extras" class="wizard-section" style="display:none;">
  <div class="wizard-title">
    <h4>Optional Extras</h4>
  </div>
  <div class="row select-extras justify-content-center">
    <div class="col-1"></div>
    <div class="col-5">
      <div class="row mb-3">
        <div class="form scheduled-description-section">
          <label><strong>Description:</strong>
            <input type="text"
                   name="description"
                   class="form-control"
                   id="scheduled-description"
                   value='<%= "#{sanitize(@change_request.description)}" if @change_request %>'>
          </label>
        </div>
      </div>
    </div>
    <div class="col-lg-5 col-md-10 extras-section" id="override-hours-form">
      <div class="form-inline">
        <label>
          <strong>Monitor Override</strong><a href="#" class="tool-tip" data-placement="top" title="When the request is carried out, temporarily pause nodes being switched off due to low CPU utilisation, for up to 8 hours." onClick="return false;"><sup>?</sup></a>:
          <input type="number"
                 min="1"
                 max="8"
                 class="form-control extras-input"
                 id="override-hours"
                 name="monitor_override_hours"
                 <%= "value=#{@change_request.monitor_override_hours}" if @change_request %>
          >  hour(s)
        </label>
      </div>
    </div>
  </div>
</div>

app/views/change_requests/_choose_when.erb
<div id="wizard-choose-when" class="wizard-section" style="display:none;">
  <div class="wizard-title">
    <h4>When?</h4>
  </div>
  <div class="row text-center select-timeframe">
    <div class="col-6">
      <div class="form-check">
        <input class="form-check-input when-radio" type="radio" name="timeframe" id="time-now" value="now" <%= 'checked' if !@change_request %>>
        <label class="form-check-label" for="time-now">
          Now (5 mins after submission)<a href="#" class="tool-tip" data-placement="top" title="Request will be carried out 5 minutes after submission." checked><sup>?</sup></a>
        </label>
      </div>
    </div>
    <div class="col-6">
      <div class="form-check">
        <input class="form-check-input when-radio" type="radio" name="timeframe" id="time-future" value="future" <%= 'checked' if @change_request %>>
        <label class="form-check-label" for="time-future">
          On chosen date(s) and time<a href="#" class="tool-tip" data-placement="top" title="Request will be carried out on the specified date and time. Can also optionally be set to repeat."><sup>?</sup></a>
        </label>
      </div>
    </div>
  </div>
  <div class="row select-when collapse<%= ' show' if @change_request %>" id="future-choice">
    <div class="col-lg-6 col-md-12">
      <div class="text-center" id="event-start-title">
        <p>
          <h5>Event Start</h5>
        </p>
      </div>
      <div class="row form-inline mb-4">
        <div class="col-4 text-left pl-0">
          Start Date:
        </div>
        <div class="col-7 request-timings text-left">
          <input type="date"
                 class="form-control request-date-picker scheduled-input"
                 id="scheduled-date"
                 min='<%= Date.current %>'
                 <%= "value=#{@change_request.date}" if @change_request %>
                 name="date">
        </div>
      </div>
      <div class="row form-inline mt-4 mb-4">
        <div class="col-4 text-left pl-0">
          Time:
        </div>
        <div class="col-7 text-left request-timings">
          <input type="time"
                 class="form-control request-time-picker scheduled-input"
                 id="scheduled-time"
                 <%= "value=#{@change_request.time}" if @change_request %>
                 name="time">
        </div>
      </div>
      <% if @change_request %>
        <div id="original-start" data-value='<%= @change_request.date_time.to_s %>'></div>
      <% end %>
    </div>
    <div class="col-lg-6 col-md-12" id="request-repeat-details">
      <div class="text-center">
        <p>
          <h5>Repetition (Optional)</h5>
        </p>
      </div>
      <%= render '/change_requests/repeat_details' %>
      <br>
    </div>
  </div>
</div>

app/views/change_requests/_dashboard_upcoming_events_table.erb
<% if locals[:events].empty? && locals[:in_progress].empty? %>
  <p class="text-center my-3">No events</p>

<% else %>

  <div class="row my-3 future-events-table text-center">
    <table class="table table-striped">

      <thead class="thead-dark events-table-header">
      <th scope="col" class="events-sub-header">Date</th>
      <th scope="col" class="events-sub-header">
        Time<a href="#" class="tool-tip timezone-tooltip" data-placement="top" title="In timezone GMT<%= Time.current.to_s.split(" ")[2] %>" onClick="return false;"><sup>?</sup>
      </a>
      <th scope="col" class="events-sub-header"> Description </th>
      <th scope="col" class="events-sub-header"> Tools </th>
      </thead>

      <tbody class="border">
      <% locals[:in_progress].each do |event| %>
        <tr class="in-progress-event-row">
          <td>
            <%= event.date %>
          </td>
          <td>
            <%= event.formatted_timestamp.split(' ').first %>
          </td>
          <td class="<%= 'budget-switch-off' if event.automated %>">
            <%= raw(event.simplified_description) + ' (in progress)' %>
          </td>
          <td></td>
        </tr>
      <% end %>

      <% locals[:events].each do |event| %>
        <tr class="<%= 'editable-event-row' if event.editable? %>"
            data-uneditable="<%= event.uneditable_date_time if event.editable? %>">
          <td>
            <%= event.date %>
          </td>
          <td>
            <%= event.time %>
          </td>
          <td class="<%= 'budget-switch-off' if event.is_a?(BudgetSwitchOffDecorator) %>">
            <%= event.description || event.auto_description %>
          </td>
          <td>
            <% if locals[:editor] %>
              <% if event.editable? %>
                <a href="events/<%= event.actual_or_parent_id %>/edit?project=<%=locals[:project_name]%>" aria-label="Edit" title="Edit">
                  <i class="fa fa-pencil fa-lg"></i>
                </a>
              <% end %>
              <% if event.cancellable? %>
                <%= link_to(raw('<i class="fa fa-trash fa-lg"></i>'),
                            {action: 'cancel',
                             controller: 'change_requests',
                             id: event.actual_or_parent_id,
                             project: event.project.name},
                            {data: { confirm: 'Are you sure you want to cancel this request?' },
                             method: :post,
                             title: "Cancel" }) %>
              <% end %>
            <% else %>
              -
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/change_requests/_event_details_card.erb
<% event = locals[:event] %>
<% parent_event = locals[:parent_event] %>
<% repeated = parent_event ? true : false %>

<div class="card event-details-card rounded-0 <%= 'border-bottom-0' if locals[:bottom_border] %>">
  <div class="event-details-text d-flex flex-row">
    <div class="event-details-column">
      <ul class="list-group list-group-flush">
        <% if repeated %>
          <li class="pb-3">
            <strong>Part of repeated event schedule: </strong><br>
            <ul class="list-group list-group-flush ml-3">
              <li>On: <%= parent_event.formatted_days %></li>
              <li>Until: <%= parent_event.parsed_end_date_time.in_time_zone(Rails.configuration.time_zone) %></li>
            </ul>
          </li>
        <% end %>

        <% event.counts.each do |group, counts| %>
          <li>
            <strong><%= group %></strong>
            <ul class="list-group list-group-flush ml-3">
              <% counts.each do |type, count| %>
                <li>
                  <%= InstanceMapping.customer_facing_type(@project.platform, type) %>:
                  <%= "#{count} nodes #{event.counts_criteria=='min' ? 'minimum' : 'exactly'}" %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
        <% unless repeated %>
          <li class="pt-3">
            <strong>Status:</strong> <%= event.status.upcase %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="event-details-column">
      <ul class="list-group list-group-flush">
        <li>
          <strong>Submitted by:</strong> <%=User.find(event.user_id).username %>
        </li>
        <li>
          <strong>Submitted at:</strong> <%= event.created_at.in_time_zone(Rails.configuration.time_zone) %>
        </li>
        <% if event.updated_at %>
          <li>
            <strong>Last edited at:</strong> <%= event.updated_at.in_time_zone(Rails.configuration.time_zone) %>
          </li>
        <% end %>
        <% if repeated %>
          <li class="pt-3">
            <strong>Status:</strong> <%= event.status.upcase %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <% if locals[:editor] %>
    <div class="row event-details-buttons justify-content-md-end text-center">
      <% if event.editable? %>
        <button class="btn btn-sm btn-warning edit-button"
                onclick="window.location.href='/events/<%= event.actual_or_parent_id %>/edit?project=<%= event.project.name %>'">
          Edit
        </button>
      <% end %>
      <% if event.cancellable? %>
        <%= button_to "Cancel",
                      {action: "cancel", id: event.actual_or_parent_id,
                       project:  event.project.name},
                      {data: { confirm: 'Are you sure you want to cancel this request?' },
                       class: "btn btn-sm btn-danger cancel-button"} %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/change_requests/_manage_events_filter.erb
<div class="row" id="manage-events-form">
  <div class="mt-1 mb-4 col-12">
    <form class="form" action="/projects/<%= @project.name %>/events" method="get" id="manage-events-filter">
      <div class="form-row justify-content-center">
        <div class="form-group col-md-3">
          <label for="groups-list">Compute Groups:</label>
          <select multiple class="form-control events-groups-select" name="groups[]" id="groups-list">
            <% @compute_groups.each do |group| %>
              <% selected = @filtered_groups && @filtered_groups&.include?(group) %>
              <option
                value='<%=group%>' <%= 'selected' if selected %>
                data-already-selected=<%= selected %>
              >
              <%= group %>
              </option>
            <% end %>
          </select>  
        </div>
      </div>
      <input type="hidden" name="project" value=<%= @project.name %>>
      <div class="form-row justify-content-center">
        <div class="form-group col-md-3">
          <input type="submit" value="Filter" class="btn btn-primary"
                 id="submit-chart-filter">
          <%= link_to "Clear all", project_events_path(@project),  class: "btn btn-danger" %>
        </div>
      </div>
    </form>
  </div>
  <div id="original-groups" data-original-groups="<%= @filtered_groups ? @filtered_groups.to_json : nil %>"></div>
</div>