config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, only: :sessions, controllers: { sessions: "sessions" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    # When user authenticated, root page is as normal
    authenticated :user do
      root 'projects#dashboard', as: :authenticated_root
    end

    # When no authenticated user, root page is the sign in page
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get '/about', to: 'sessions#about'
    end
  end

  # About page
  get '/about', to: 'sessions#about'

  # Projects
  get '/dashboard', to: 'projects#dashboard'
  get '/costs-breakdown', to: 'projects#costs_breakdown'
  get '/billing-overview', to: 'projects#billing_overview'
  get '/policies', to: 'projects#policy_page'
  get '/audit', to: 'projects#audit'
  get '/json/data-check', to: 'projects#data_check'
  get '/json/audit-logs', to: 'projects#audit_logs'
  post '/config-update', to: 'projects#config_update'

  # Events (change requests and their resulting actions)
  get '/events', to: 'change_requests#manage'
  get '/events/new', to: 'change_requests#new'
  get '/events/:id/edit', to: 'change_requests#edit', as: :event_edit
  get '/json/events/latest', to: 'change_requests#latest'
  get '/json/events/costs-forecast', to: 'change_requests#costs_forecast'
  post '/events/', to: 'change_requests#create'
  post '/events/:id/cancel', to: 'change_requests#cancel'
  post '/events/:id/update', to: 'change_requests#update'
  post '/dashboard/:id/cancel', to: 'change_requests#cancel'

  authenticate :user, lambda {|u| u.admin? } do
    mount Resque::Server.new, :at => "/resque"
  end
end

app/views/partials/_action_log_card.erb
<% log = locals[:log] %>
<% header_class = log && log.automated? ? "automated-action-header" : "action-header" %>
<div class="card audit-log action-log">
  <div class="card-header <%= header_class %> text-white d-inline-flex justify-content-between align-items-center ">
    <span class="action-log-type"><%= log && log.automated ? "Automated Action Log" : "Action log" %></span>
    <span class="log-timestamp" data-value='<%=log.created_at if log%>'><%= log.formatted_timestamp if log%></span>
  </div>
  <div class="card-body">
    <p class="card-text">
      <%= log.card_description.html_safe if log%>
    </p>
  </div>
  <div class="card-footer text-right">
    Status: <strong class="action-status"><%= log.status if log%></strong>
  </div>
</div>

app/views/partials/_audit_logs.erb
<% locals[:logs].each do |log| %>
  <div class="row audit-row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <%= render "partials/#{log.partial}", locals: {log: log} %>
    </div>
  </div>
<% end %>

app/views/partials/_change_request_audit_log_card.erb
<% log = locals[:log] %>
<% header_class = log && log.cancellation? ? "request-cancel-header" : "request-change-header" %>
<div class="card audit-log request-change-log">
  <div class="card-header <%= header_class %> d-inline-flex justify-content-between align-items-center ">
    <span>Change request updated by <b class="cr-username"><%=User.find(log.user_id).username if log%></b></span>
    <span class="log-timestamp" data-value='<%=log.created_at if log%>'><%= log.formatted_timestamp if log%></span>
  </div>
  <div class="card-body">
    <div class="card-text">
      <%= log.card_description.html_safe if log %>
    </div>
  </div>
  <div class="card-footer text-right">
    Status: <strong class="change-status"><%= log.status if log%></strong>
  </div>
</div>

app/views/partials/_change_request_card.erb
<% log = locals[:log].as_original if locals[:log] %>
<div class="card audit-log change-request-log">
  <div class="card-header change-request-header d-inline-flex justify-content-between align-items-center ">
    <span>Change request submitted by <b class="cr-username"><%=User.find(log.user_id).username if log%></b></span>
    <span class="log-timestamp" data-value='<%=log.created_at if log%>'><%= log.formatted_timestamp if log%></span>
  </div>
  <div class="card-body">
    <div class="card-text">
      <%= log.card_description.html_safe if log %>
    </div>
  </div>
  <div class="card-footer d-flex justify-content-between">
    <div class="edit-request-link">
      <% if log && log.editable? %>
        <a href="/events/<%= log.id %>/edit?project=<%= @project.name %>">Edit request</a>
      <% end%>
    </div>
    <div>Status: <strong class="change-status"><%= log.status if log%></strong></div>
  </div>
</div>

app/views/partials/_config_log_card.erb
<% log = locals[:log] %>
<div class="card audit-log config-log">
  <div class="card-header config-log-header d-inline-flex justify-content-between align-items-center ">
    <span class="config-log-source">
      <% if log&.automated %>
        <% request_link = log.change_request.editable? ? "<a href='/events/#{log.change_request_id}/edit?project=#{@project.name}' >change request.</a>" : "change request" %>
        Project configuration updated as part of a <%= request_link.html_safe %>
      <% else %>
        Project configuration change submitted by <b class="config-username"><%= log.user.username if log%></b>
      <% end %>
    </span>
    <span class="log-timestamp" data-value='<%=log.created_at if log%>'><%= log.formatted_timestamp if log%></span>
  </div>
  <div class="card-body">
    <div class="card-text">
      <%= log.card_description.html_safe if log %>
    </div>
  </div>
  <div class="card-footer text-right">
    Status: <strong class="log-status"><%= log.status if log%></strong>
  </div>
</div>

app/views/partials/_dashboard_group_card.erb
<div class="card dashboard-card mb-4 groups <%= "core" if locals[:compute_group] == "core"%>">
  <div class="card-body d-flex flex-column">

    <!-- Card heading -->
    <div class="row justify-content-center">
      <h4 class="card-title text-center groups-card-heading"><%= locals[:compute_group].capitalize %></h4>
    </div>

    <!-- Group data -->
    <ul class="list-group list-group-flush <%= "core" if locals[:compute_group] == "core" %>">
      <li class="list-group-item dashboard-list-item">
        <strong>Status:</strong> <%= locals[:status] %>
      </li>
      <li class="list-group-item dashboard-list-item pb-3">
        <strong>
          Cost this cycle<a href="#"
                            class="tool-tip <%= "core" if locals[:compute_group] == "core"%>"
                            data-placement="top"
                            title="As of the start of today. Includes some estimation."
                            onClick="return false;"><sup>?</sup></a>:
        </strong> <%= locals[:cost_this_cycle] %> c.u.
      </li>
    </ul>

    <!-- Buttons -->
    <div class="row justify-content-md-center mt-auto text-center">
      <% unless locals[:compute_group] == "core" %>
        <% disable = locals[:end_date] && locals[:end_date] < Date.today %>
        <%= link_to 'Events',
                    project_events_path(@project, groups: [locals[:compute_group]]),
                    class: "btn btn-warning dashboard-btn groups #{'disabled' if disable}",
                    role: "button",
                    onClick: "return #{!disable}"
        %>
      <% end %>
      <%= link_to 'Costs',
                  project_costs_breakdown_path(@project, datasets: [locals[:compute_group]]),
                  class: "btn btn-info dashboard-btn groups #{'core' if locals[:compute_group] == 'core'}",
                  role: "button"
      %>
      <% unless locals[:compute_group] == "core" %>
        <%= link_to 'Logs',
                    project_audit_path(@project, groups: [locals[:compute_group]]),
                    role: "button",
                    class: "btn btn-info dashboard-btn groups"
        %>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_dashboard_overview_list_item.erb
<li class="list-group-item dashboard-list-item <%= "pb-3" if locals[:padding] %>">
  <strong>
    <%= locals[:field] %><!--
    <% if locals[:description] %>
      --><a href="#"
            class="tool-tip"
            data-placement="top"
            title="<%= locals[:description] %>"
            onClick="return false;"><sup>?</sup></a><!--
    <% end %>-->:
  </strong>
  <span <%= 'class=text-danger' if locals[:red] %>>
    <%= locals[:value] %>
  </span>
</li>

app/views/partials/_flashes.erb
<% flash.each do |type, msg| %>
  <div data-alert class="alert alert-<%= flash_class(type.to_s) %> mt-2 m-2 alert-dismissable fade show" role="alert">
    <%= msg.html_safe %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/partials/_funds_transfer_request_card.erb
<% log = locals[:log] %>
<div class="card audit-log funds-transfer-log">
  <div class="card-header funds-transfer-header text-white d-inline-flex justify-content-between align-items-center">
    Funds Transfer Request
    <span class="log-timestamp" data-value='<%=log.created_at if log%>'><%= log.formatted_timestamp if log%></span>
  </div>
  <div class="card-body">
    <p class="card-text">
      <%= log.card_description.html_safe if log%>
    </p>
  </div>
  <div class="card-footer text-right">
    Status:
    <strong class="action-status <%= "text-danger" if log && log.failed? %>"><%= log.status if log%></strong>
  </div>
</div>

app/views/partials/_history.erb
<% if @list.first_logs.any? %>
  <div class="audit-logs">
    <div class="row">
      <div class="col-sm-3"></div>
      <div class="col-sm-6">
        <h3 class="mr-auto p-2 audit-logs-title">
          History
        </h3>
      </div>
    </div>
    <%= render "partials/audit_logs", locals: {logs: @list.first_logs} %>
    <% if @list.more_logs? %>
      <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6 text-center">
          <button
            class="btn btn-primary"
            id="load-more-logs"
            data-project="<%= @project.name %>"
            data-types="<%= @list.types.join(',') %>"
            <%= "data-users=#{@list.users.join(',')}" if @list.users %>
            <%= "data-statuses=#{@list.statuses.join(',')}" if @list.statuses %>
            <%= "data-groups=#{@list.groups.join(',')}" if @list.groups %>
            <%= "data-start_date=#{@list.start_date}"  if @list.start_date %>
            <%= "data-end_date=#{@list.end_date}"  if @list.end_date %>
          > Load more </button>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/partials/_nav.erb
<ul class="top nav view-selection">
  <% if current_user && @project %>
    <li class="top nav-item">
      <%= link_to "DASHBOARD", dashboard_path(project: @project.name), class: "top nav-link#{' active' if @nav_view == "dashboard"}" %>
    </li>
    <%= render '/partials/nav_dropdown', locals: {dropdown_id: 'costsDropdownButton', dropdown_text: 'COSTS', active_nav_options: %w(billing costs)} do %>
      <%= link_to "Billing overview", billing_overview_path(project: @project.name), class: "top nav-link#{' active' if @nav_view == "billing"}" %>
      <%= link_to "Costs breakdown", costs_breakdown_path(project: @project.name), class: "top nav-link#{' active' if @nav_view == "costs"}" %>
    <% end %>

    <% can_create_event = ChangeRequestPolicy.new(current_user, ChangeRequest.new(project: @project)).create? %>
    <% can_manage_events = ChangeRequestPolicy.new(current_user, ChangeRequest.new(project: @project)).manage? %>
    <% if can_create_event || can_manage_events %>
      <%= render '/partials/nav_dropdown', locals: {dropdown_id: 'eventsDropdownButton', dropdown_text: 'EVENTS', active_nav_options: ["event wizard", "manage events"]} do %>
        <% if can_create_event %>
          <% title = @change_request ? "Edit event" : "Create event" %>
          <%= link_to title, events_new_path(project: @project.name), class: "top nav-link#{' active' if @nav_view == "event wizard"}" %>
        <% end %>
        <% if can_manage_events %>
          <%= link_to "Manage events", events_path(project: @project.name), class: "top nav-link#{' active' if @nav_view == "manage events"}" %>
        <% end %>
      <% end %>
    <% end %>

    <% if ProjectPolicy.new(current_user, @project).policy_page? %>
      <li class="top nav-item">
        <%= link_to "POLICIES", policies_path(project: @project.name), class: "top nav-link#{' active' if @nav_view == "policies"}" %>
      </li>
    <% end %>
    <% if ProjectPolicy.new(current_user, @project).audit? %>
      <li class="top nav-item">
        <%= link_to "AUDIT", audit_path(project: @project.name), class: "top nav-link#{' active' if @nav_view == "audit"}" %>
      </li>
    <% end %>
  <% end %>
  <li class="top nav-item">
    <%= link_to "ABOUT", about_path, class: "top nav-link#{' active' if @nav_view == "about"}" %>
  </li>
</ul>

app/views/partials/_nav_dropdown.html.erb
<li class="top nav-item dropdown">
  <a
    class="dropdown-toggle top nav-link <%= 'active' if locals[:active_nav_options]&.include?(@nav_view) %>"
    id="<%= locals[:dropdown_id] %>"
    data-toggle="dropdown"
    aria-haspopup="true"
    aria-expanded="false">
    <%= locals[:dropdown_text] %>
  </a>
  <div class="dropdown-menu" aria-labelledby="<%= locals[:dropdown_id] %>">
    <%= yield %>
  </div>
</li>

app/views/partials/_project_nav.erb
<% if current_user && current_user.multi_project_user? %>
  <% projects = current_user.projects.reorder(:name) %>
  <nav class="col-md-2 bg-light sidebar" id="project-nav">
    <div class="sidebar-sticky flush">
      <div class="list-group">
        <% if projects.any? { |p| !p.archived? } %>
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-2 text-muted">
            <span>ACTIVE PROJECTS</span>
          </h6>
          <% projects.each do |project| %>
            <% if !project.archived? %>
              <% klass = "list-group-item list-group-item-action project-link #{'active' if project.name == @project.name}" %>
              <%= link_to project.name, project_dashboard_path(project), class: klass %>
            <% end %>
          <% end %>
        <% end %>

        <% if projects.any? { |p| p.archived? } %>
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-2 text-muted">
            <span>ARCHIVED PROJECTS</span>
          </h6>
          <% projects.each do |project| %>
            <% if project.archived? %>
              <% klass = "list-group-item list-group-item-action project-link #{'active' if project.name == @project.name}" %>
              <%= link_to project.name, project_dashboard_path(project), class: klass %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </nav>
<% end %>

app/views/partials/_title.erb
<div class="page-title text-center">
  <h1>
    <strong class="blue-text"><%= locals[:project_name] %></strong> <%= locals[:title_text] %>
  </h1>
</div>