config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, only: :sessions, controllers: { sessions: "sessions" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    # When user authenticated, root page is as normal
    authenticated :user do
      root 'projects#dashboard', as: :authenticated_root
    end

    # When no authenticated user, root page is the sign in page
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get '/about', to: 'sessions#about'
    end
  end

  # About page
  get '/about', to: 'sessions#about'

  # Projects
  get '/dashboard', to: 'projects#dashboard'
  get '/costs-breakdown', to: 'projects#costs_breakdown'
  get '/billing-overview', to: 'projects#billing_overview'
  get '/policies', to: 'projects#policy_page'
  get '/audit', to: 'projects#audit'
  get '/json/data-check', to: 'projects#data_check'
  get '/json/audit-logs', to: 'projects#audit_logs'
  post '/config-update', to: 'projects#config_update'

  # Events (change requests and their resulting actions)
  get '/events', to: 'change_requests#manage'
  get '/events/new', to: 'change_requests#new'
  get '/events/:id/edit', to: 'change_requests#edit', as: :event_edit
  get '/json/events/latest', to: 'change_requests#latest'
  get '/json/events/costs-forecast', to: 'change_requests#costs_forecast'
  post '/events/', to: 'change_requests#create'
  post '/events/:id/cancel', to: 'change_requests#cancel'
  post '/events/:id/update', to: 'change_requests#update'
  post '/dashboard/:id/cancel', to: 'change_requests#cancel'

  authenticate :user, lambda {|u| u.admin? } do
    mount Resque::Server.new, :at => "/resque"
  end
end

app/models/project.rb
require_relative 'balance'
require_relative 'budget_policy'
require_relative 'instance_log'
require_relative 'cost_log'
require_relative 'action_log'
require_relative '../services/project_config_creator'
require_relative '../services/costs_plotter'
require_relative '../services/instance_tracker'
require_relative '../decorators/budget_switch_off_decorator'
require 'httparty'

class Project < ApplicationRecord
  BUDGET_SWITCH_OFF_TIME = "23:30"
  DEFAULT_COSTS_DATE = Date.current - 3
  SCOPES = %w[total data_out core core_storage]
  has_many :instance_logs
  has_many :cost_logs
  has_many :action_logs
  has_many :config_logs
  has_many :change_requests
  has_many :change_request_audit_logs
  has_many :one_off_change_requests
  has_many :repeated_change_requests
  has_many :balances
  has_many :budget_policies
  has_many :user_roles

  before_save :set_type, if: Proc.new { |p| !p.persisted? || p.platform_changed? }
  validates :name, presence: true, uniqueness: true
  validates :name, :format => { with: /\A[a-zA-Z]+[0-9a-zA-Z_-]*[0-9a-zA-Z]+\z/,
            message: 'Must start with letters and only include letters, numbers, dashes or underscores.' }
  validates :slack_channel, :start_date, :filter_level, :security_id, :security_key,
            :type, presence: true
  validate :end_date_after_start, on: [:update, :create], if: -> { end_date != nil }
  validates :platform,
    presence: true,
    inclusion: {
      in: %w(aws azure example),
      message: "%{value} is not a valid platform"
    }
  after_save :update_end_balance
  scope :active, -> { where("archived_date IS NULL OR archived_date > ?", Date.current) }
  scope :visualiser, -> { where(visualiser: true) }

  def self.slack_token
    @@slack_token ||= Rails.application.config.slack_token
  end

  def archived?
    # use !! so returns false instead nil, which confuses table print
    !!(archived_date && archived_date <= Date.current)
  end

  def latest_instance_logs
    instance_logs.where(date: instance_logs.maximum(:date))
  end

  def pending_actions?
    if @pending_actions == nil
      @pending_actions = pending_action_logs.exists?
    end
    @pending_actions
  end

  def pending?
    if @pending == nil
      @pending = (pending_actions? || pending_one_off_and_repeat_requests.any?)
    end
    @pending
  end

  # Run this only when new instance logs are created (as we know
  # statuses can't have changed unless instance statuses have changed)
  def check_and_update_pending_changes
    change_requests.where.not(status: "complete").where.not(
                              status: "cancelled").reorder(
                              "updated_at DESC").each { |request| request.check_and_update_status }
    action_logs.where(change_request_id: nil, status: "pending").each { |action| action.check_and_update_status }
  end

  def pending_one_off_change_requests
    one_off_change_requests.where(status: "pending")
  end

  # For repeat requests, they are pending (but don't necessarily have a 
  # status of pending) until all their actions on every date are complete
  def pending_repeated_requests
    repeated_change_requests.where.not(status: "complete").where.not(status: "cancelled")
  end

  def pending_repeated_request_children
    if !@repeated_request_children
      @repeated_request_children = pending_repeated_requests.map { |repeated| repeated.as_future_individual_requests }.flatten
    end
    @repeated_request_children
  end

  def pending_one_off_and_repeat_requests
    if !@combined_requests
      @combined_requests = pending_one_off_change_requests.to_a.concat(pending_repeated_request_children).compact
      @combined_requests = @combined_requests.sort_by { |request| [request.date, request.time] }
    end
    @combined_requests
  end

  def pending_one_off_and_repeat_requests_on(date, groups=nil)
    pending = pending_one_off_change_requests.where(date: date)
    pending = pending.to_a.select { |request| request.included_in_groups?(groups) } if groups
    repeated = pending_repeated_requests.select do |repeat|
      repeat.action_on_date?(date) && (!groups ||
      repeat.included_in_groups?(groups))
    end
    repeated_children = repeated.map { |repeat| repeat.individual_request_on_date(date) }
    pending.to_a.concat(repeated_children).compact
  end

  def request_dates_and_times(exclude_request=nil)
    results = {}
    requests = pending_one_off_and_repeat_requests
    requests.reject! { |request| request.actual_or_parent_id == exclude_request.actual_or_parent_id } if exclude_request
    requests.pluck(:date, :time).each do |timing|
      date = timing[0]
      time = timing[1]
      if results[date]
        results[date][time] = true
      else
        results[date] = {time => true }
      end
    end
    results
  end

  # In future this will include over budget switch offs
  def events(groups=nil, recalculate_budget_off=true)
    events = pending_one_off_and_repeat_requests.concat(decorated_switch_offs(recalculate_budget_off))
    events = events.select { |event| event.included_in_groups?(groups) } if groups
    events
  end

  def events_on(date, groups=nil)
    requests = pending_one_off_and_repeat_requests_on(date, groups)
    switch_offs = decorated_switch_offs.select { |off| off.date == date && (!groups || off.included_in_groups?(groups)) }
    requests.concat(switch_offs)
  end

  def events_by_date(chosen_events=events)
    chosen_events.sort_by {|e| [e.date, e.time]}.group_by {|e| e.date}
  end

  # within next 5 mins
  def upcoming_events(groups=nil)
    today_events = events_on(Date.current, groups)
    five_mins_from_now = Time.current + 5.minutes
    today_events.select { |event| event.date_time <= five_mins_from_now }
  end

  def upcoming_events_by_date(groups=nil)
    events_by_date(upcoming_events(groups))
  end

  # after next 5 mins
  def future_events(groups=nil, recalculate_budget_off=true)
    five_mins_from_now = Time.current + 5.minutes
    future = events(groups, recalculate_budget_off)
    future.select { |event| event.date_time > five_mins_from_now }
  end

  def future_events_by_date(groups=nil, recalculate_budget_off=true)
    events_by_date(future_events(groups, recalculate_budget_off))
  end

  def events_by_id(events)
    results = {}
    events.each do |date, events|
      results[date] = {}
      events.each do |event|
        results[date][event.front_end_id] = event
      end
    end
    results
  end

  # For front end use and in cost forecast calculations
  def latest_instances(temp_change_request=nil)
    if !@instances || temp_change_request
      @instances = InstanceTracker.new(self).latest_instances(temp_change_request)
    end
    @instances
  end

  def nodes_up
    InstanceTracker.new(self).nodes_up
  end
  
  def missing_instance_details?
    latest_instances.each do |_, instances|
      instances.each do |instance|
        return true if instance.missing_details?
      end
    end
    false
  end

  def missing_instance_details_flash
    "Values displayed based on incomplete or invalid instance details. \n
    Please ask an administrator to generate new instance detail records."
  end

  # For resetting after temp
  def reset_latest_instances
    @instances = nil
  end

  def pending_action_logs
    action_logs.where(status: "pending")
  end

  def current_balance
    balances.where("effective_at <= ?", Date.current).last
  end

  def current_budget_policy
    @budget_policy ||= budget_policies.where("effective_at <= ?", Date.current).last
  end

  def cycle_days
    current_budget_policy.days
  end

  def cycle_interval
    current_budget_policy.cycle_interval
  end

  def current_compute_groups
    @current_groups ||= latest_instance_logs.pluck(Arel.sql("DISTINCT compute_group")).compact
  end

  def has_config_file?
    File.file?((File.join(Rails.root, 'config', 'projects', "#{name}.yaml")))
  end

  def settings
    if !@settings
      if has_config_file?
        @settings = YAML.load(File.read(File.join(Rails.root, 'config', 'projects', "#{name}.yaml")))
      else
        @settings = YAML.load(File.read(File.join(Rails.root, 'config', 'projects', "default.yaml")))
      end
    end
    @settings
  end

  def front_end_compute_groups
    settings["compute_groups"]
  end

  def compute_groups_on_date(date)
    logs = instance_logs.where(date: date)
    # If no logs on that, get most recent earlier logs
    if !logs.exists?
      latest_date = instance_logs.where("date < ?", date).maximum(:date)
      if latest_date
        logs = instance_logs.where(date: latest_date)
      else
        return []
      end
    end
    logs.pluck(Arel.sql("DISTINCT compute_group")).compact.compact
  end

  def create_config_file(overwrite=false)
    ProjectConfigCreator.new(self).create_config_file(overwrite)
  end

  def time_of_latest_change
    latest_cost_data = cost_logs.maximum("updated_at") if cost_logs.exists?
    latest_instance_data = instance_logs.maximum("last_status_change") if instance_logs.exists?
    latest_action_log = action_logs.maximum("updated_at") if action_logs.exists?
    latest_change_request = change_requests.maximum("updated_at") if change_requests.exists?
    if latest_cost_data || latest_instance_data || latest_action_log || latest_change_request
      latest = [latest_cost_data, latest_instance_data, latest_action_log, latest_change_request].compact.max
    else
      latest = Date.current.to_time
    end
    latest
  end

  # Timestamps are stored in db with more precision than can be easily represented,
  # so a parsed string will not necessarily equal the same time (as we see it) in the db.
  # To get around this we case the Times to ints to remove some of the precision.
  def data_changed?(timestamp)
    time_of_latest_change.to_i > timestamp.to_i
  end

  def record_instance_logs(rerun=false, verbose=false)
    # can't record instance logs if resource group deleted
    if archived?
      return "Logs not recorded, project is archived"
    end
    
    outcome = ""

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def dashboard
    get_project
    if !@project
      no_project_redirect
    else
      authorize @project, policy_class: ProjectPolicy
      @nav_view = "dashboard"
      get_billing_data
      get_upcoming_events
      get_group_data
      check_missing_instance_details
    end
  end

  def costs_breakdown
    get_project
    if !@project
      no_project_redirect
    else
      authorize @project, policy_class: ProjectPolicy
      @nav_view = "costs"
      get_costs_data
    end
  end

  def policy_page
    get_project
    if !@project
      no_project_redirect
    else
      authorize @project, policy_class: ProjectPolicy
      @nav_view = "policies"
    end
  end

  def audit
    get_project
    if !@project
      no_project_redirect
    else
      authorize @project, policy_class: ProjectPolicy
      @list = AuditLogList.new(@project, params)
      @nav_view = "audit"
    end
  end

  def audit_logs
    get_project
    if !@project
      no_project_redirect
    else
      authorize @project, policy_class: ProjectPolicy
      latest_timestamp = Time.parse(params['timestamp'])
      log_count = params['log_count'].to_i
      filters = {"groups" => params['groups'],
                 "types" => params['types'],
                 "users" => params['users'],
                 "statuses" => params['statuses'],
                 "start_date" => params["start_date"],
                 "end_date" => params["end_date"]
                }
      list = AuditLogList.new(@project, filters)
      logs, more = list.next_logs(log_count, latest_timestamp)
      render json: {logs: logs, more: more}
    end
  end

  def config_update
    get_project
    if !@project
      no_project_redirect
    else
      authorize @project, policy_class: ProjectPolicy
      details = params.permit(config: {})["config"]
      result = @project.submit_config_change(details, current_user)
      if result.valid? && result.persisted?
        flash[:success] = "Config change submitted"
      else
        flash[:danger] = result.errors.full_messages.join(", ")
      end
      redirect_to policies_path(project: @project.name)
    end
  end

  def billing_overview
    get_project
    if !@project
      no_project_redirect
    else
      @nav_view = "billing"
      authorize @project, policy_class: ProjectPolicy
      get_billing_data
      check_missing_instance_details
    end
  end

  def data_check
    get_project
    if !@project
      no_project_redirect
    else
      authorize @project, policy_class: ProjectPolicy
      timestamp = Time.parse(params['timestamp'])
      render json: {changed: @project.data_changed?(timestamp)}
    end
  end

  def get_billing_data
    @policy = @project.budget_policies.last
    @billing_date = cost_plotter.billing_date
    @latest_cycle_details = cost_plotter.latest_cycle_details
  end

  def get_upcoming_events
    @editor = ChangeRequestPolicy.new(current_user, ChangeRequest.new(project: @project)).create?
    @in_progress = @project.pending_action_logs
                           .sort_by {|log| [log.compute_group, log.customer_facing_type]}
                           .first(5)
    if @in_progress.length < 5
      @sorted_events = @project.events
                               .sort_by { |event| [event.date, event.time] }
                               .first(5 - @in_progress.length)
    else
      @sorted_events = []
    end
  end

  def get_group_data
    compute_groups = @project.front_end_compute_groups.keys
    @group_costs = cost_plotter.total_costs_this_cycle( ['core'] + compute_groups )
    @nodes_up = @project.nodes_up
  end

  def get_costs_data
    if params['start_date'] && params['start_date'] != ""
      @start_date = Date.parse(params['start_date'])
    else
      @start_date = cost_plotter.start_of_billing_interval(Date.current)
    end
    if params['end_date'] && params['end_date'] != ""
      @end_date = Date.parse(params['end_date'])
    else
      @end_date = cost_plotter.end_of_billing_interval(@start_date)
    end
    costs = cost_plotter.combined_cost_breakdown(@start_date, @end_date, nil, true)
    @cost_breakdown = cost_plotter.chart_cost_breakdown(@start_date, @end_date, nil, costs)
    @cumulative_costs = cost_plotter.chart_cumulative_costs(@start_date, @end_date, nil, costs)
    @possible_datasets = cost_plotter.possible_datasets
    @datasets = params['datasets']
    @current_instances = @project.latest_instances
    @cycle_thresholds = cost_plotter.cycle_thresholds(@start_date, @end_date)
    @min_date = cost_plotter.minimum_date
    @max_date = cost_plotter.date_limit
    @switch_offs = cost_plotter.front_end_switch_offs_by_date(@start_date, @end_date, false)
    @estimated_end_of_balance = cost_plotter.estimated_balance_end_in_cycle(@start_date, @end_date, costs)
    filter_current_instances if @datasets
    check_missing_instance_details
  end

  private

  # Only include filtered groups, or all if none selected
  def filter_current_instances
    original = @current_instances.clone
    @current_instances.select! { |group, instances| @datasets.include?(group) }
    @current_instances = original if @current_instances.empty?
  end

  def cost_plotter
    @cost_plotter ||= @project.costs_plotter
  end

  def no_project_redirect
    render "projects/no_project"
  end
end

app/views/projects/_audit_filter_form.erb
<div class="row">
  <% if current_user.multi_project_user? %>
    <div class="col-sm-1"></div>
    <div class="mt-4 ml-4 col-10" >
  <% else %>
    <div class="col-sm-2"></div>
    <div class="mt-4 ml-4 col-9" >
  <% end %>
    <form class="form" action="/audit" method="get" id="audit-logs-filter">
      <div class="form-row">
        <div class="form-group col-md-2">
          <label for="log-types" class="audit-form-label">Groups:</label>
          <select multiple class="form-control audit-select" name="groups[]" id="log-groups-list">
            <% @project.front_end_compute_groups.pluck(:name).each do |group| %>
              <% selected = @list && @list.filters["groups"]&.include?(group) %>
              <option
                value=<%=group%> <%= 'selected' if selected %>
                data-already-selected=<%= selected %>
              >
              <%= group %>
              </option>
            <% end %>
          </select>  
        </div>
        <div class="form-group col-md-2">
          <label for="log-types" class="audit-form-label">Log Types:</label>
          <select multiple class="form-control audit-select" name="types[]" id="log-types-list">
            <% AuditLogList::LOG_TYPES.each do |klass, description| %>
              <% selected = @list && @list.filters["types"]&.include?(klass) %>
              <option
                value=<%=klass%> <%= 'selected' if selected %>
                data-already-selected=<%= selected %>
              >
              <%= description %>
              </option>
            <% end %>
          </select>  
        </div>
        <div class="form-group col-md-2">
          <label for="users-list" class="audit-form-label">Users:</label>
          <select multiple class="form-control audit-select" name="users[]" id="users-list">
            <% users = @project.all_associated_users.pluck(:username) %>
            <% users << "automated" %>
            <% users.sort.each do |username| %>
              <% selected = @list && @list.users&.include?(username) %>
              <option
                value=<%=username%> <%= 'selected' if selected %>
                data-already-selected=<%= selected %>
              >
              <%= username %>
              </option>
            <% end %>
          </select>
        </div>
        <div class="form-group col-md-2">
          <label for="users-list" class="audit-form-label">Status:</label>
           <select multiple class="form-control audit-select" name="statuses[]" id="status-list">
            <% AuditLogList::POSSIBLE_STATUSES.each do |status| %>
              <% selected = @list && @list.statuses&.include?(status) %>
              <option
                value=<%=status%> <%= 'selected' if selected %>
                data-already-selected=<%= selected %>
              >
                <%= status %>
              </option>
            <% end %>
          </select>
        </div>
        <div class="form-group col-md-2">
          <label for="from-date" class="audit-form-label">From:</label>
          <input class="form-control" type="date" id='from-date'
                 name='start_date' max=<%=Date.current%>
                 <%= "value=#{@list.start_date}" if @list.start_date %>>
        </div>
        <div class="form-group col-md-2">
          <label for="to-date" class="audit-form-label">To:</label>
          <input class="form-control" type="date" id='to-date'
                 name="end_date" max=<%=Date.current%>
                 <%= "value=#{@list.end_date}" if @list.end_date %>>
        </div>
      </div>
      <input type="hidden" name="project" value=<%= @project.name %>>
      <div class="form-row align-items-center">
        <div class="form-group col-md-4">
          <input type="submit" value="Filter" class="btn btn-primary">
          <a href="/audit?project=<%= @project.name %>" class="btn btn-danger">Clear all</a>
        </div>
      </div>
    </form>
  </div>
</div>

app/views/projects/_billing_history_chart.erb
<% project = @project.decorate %>
<% year_options = project.billing_history_years %>
<% latest_year = year_options.max %>

<h2 class="ml-2 mb-4 text-center">Billing History</h2>

<div class="chart-container">
  <%= select_tag :years, options_for_select(year_options, latest_year), { onchange: 'changeYear()', class: "form-control" } %>
  <canvas id="billingHistoryChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation/dist/chartjs-plugin-annotation.min.js"></script>
<script>
  let year = <%= raw(latest_year) %>;
  const allData = <%= raw(project.billing_chart_data.to_json) %>;
  const allTooltips = <%= raw(project.billing_chart_tooltips.to_json) %>;
  const allCycles = <%= raw(project.billing_cycle_dates.to_json) %>;
  const projectName = <%= raw(project.name.to_json) %>;
  const gridColour = '#CFEDFA';
  const borderColour = '#AEC7D7';
  const alcesBlue = '#2693D7';
  const currentCycleGreen = '#5FD094';

  const ctx = document.getElementById('billingHistoryChart');
  let chart = new Chart(ctx, {
    type: 'line',
    data: {
      datasets: [{
        data: allData[year],
        borderWidth: 2,
        tooltips: allTooltips[year],
      }]
    },
    options: {
      clip: false,
      scales: {
        y: {
          beginAtZero: true,
          title: {
            display: true,
            text: 'Total (cu)',
            font: {
              size: 20,
            },
            padding: {
              bottom: 20
            }
          },
          ticks: {
            font: {
              size: 16,
            },
            maxTicksLimit: 8
          },
          grid: {
            color: gridColour
          },
          border: {
            color: borderColour
          }
        },
        x: {
          title: {
            display: true,
            text: 'Billing date',
            font: {
              size: 20,
            },
            padding: {
              top: 20
            }
          },
          ticks: tickLabelProperties(year),
          grid: {
            color: gridColour
          },
          border: {
            color: borderColour
          },
          type: 'time',
          time: {
            unit: 'month',
            displayFormats: {
              'week': 'DD.MM',
              'month': 'do MMM',
              'year': 'MMMM',
            },
          },
          min: minDate(year),
          max: maxDate(year),
        }
      },
      elements: {
        point: {
          pointBorderColor: pointColours(year),
          pointBorderWidth: 4,
          pointBackgroundColor: '#ffffff',
          pointRadius: 5,
          pointHitRadius: 5
        }
      },
      plugins: {
        clip: false,
        annotation: {
          annotations: {
            current: {
              type: 'line',
              xMin: currentCycle(),
              xMax: currentCycle(),
              borderColor: 'transparent',
              borderWidth: 1,
              label: {
                display: true,
                content: ['(forecast)'],
                position: 'start',
                backgroundColor: 'transparent',
                color: currentCycleGreen,
                font: {
                  size: 16
                },
                yAdjust: 63,
              }
            }
          }
        },
        legend: {
          display: false
        },
        tooltip: {
          displayColors: false,
          bodyAlign: 'center',
          yAlign: 'bottom',
          bodyFont: {
            size: 16
          },
          callbacks: {
            title: function () {
              return ""
            },
            label: function (context) {
              return context.dataset.tooltips[context.dataIndex];
            }
          }
        }
      }
    }
  });

  document.getElementById('billingHistoryChart').onclick = function(evt){
    let clickedPoint = chart.getElementsAtEventForMode(evt, 'nearest', { intersect: true }, true);
    if (clickedPoint.length !== 0) {
      const index = clickedPoint[0]['index'];
      let year = selectedYear();
      const cycleStart = allCycles[year][index]['start'];
      const cycleEnd = allCycles[year][index]['end'];
      window.open(`costs-breakdown?start_date=${cycleStart}&end_date=${cycleEnd}&project=${projectName}`);
    }
  };

  function changeYear() {
    let year = selectedYear();
    chart.data.datasets.forEach(function(dataset) {
      dataset.data = allData[year];
      dataset.tooltips = allTooltips[year];
    });
    chart.options.scales.x.min = minDate(year);
    chart.options.scales.x.max = maxDate(year);
    chart.options.scales.x.ticks = tickLabelProperties(year);
    chart.options.elements.point.pointBorderColor = pointColours(year);
    chart.update('none');
  }

  function selectedYear() {
    return Number(document.getElementById("years").value);
  }

  function minDate(year) {
    return `${year - 1}-12-20`;
  }

  function maxDate(year) {
    return `${year}-12-31`;
  }

  function currentCycle() {
    const now = new Date();
    const yearData = allData[now.getFullYear()];
    if (yearData !== undefined) {
      const latestCycleBillingDate = yearData[yearData.length - 1]['x'];
      if (new Date(latestCycleBillingDate).getTime() > now.getTime()) {
        return latestCycleBillingDate;
      }
    }
    return 0;
  }

  function pointColours(year) {
    const chartData = allData[year];
    const numPoints = chartData.length;
    let colours = [];
    if (new Date(chartData[numPoints - 1]['x']).getTime() > new Date().getTime()) {
      for (let i = 0; i < numPoints-1; i++) {
        colours.push(alcesBlue);
      }
      colours.push(currentCycleGreen);
    } else {
      colours = alcesBlue;
    }
    return colours;
  }

  function tickLabelProperties(year) {
    const standardColor = '#666';
    const standardWeight = 'normal';
    const chartData = allData[year];
    const numPoints = chartData.length;
    let colours = [];
    let weights = [];
    if (new Date(chartData[numPoints - 1]['x']).getTime() > new Date().getTime()) {
      for (let i = 0; i < numPoints-1; i++) {
        colours.push(standardColor);
        weights.push(standardWeight);
      }
      colours.push(currentCycleGreen);
      weights.push('bold');
      for (let i = 0; i < (12 - numPoints); i++) {
        colours.push(standardColor);
        weights.push(standardWeight);
      }
    } else {
      colours = standardColor;
      weights = standardWeight;
    }
    return {
      color: colours,
      font: {
        size: 16,
        weight: weights,
      }
    };
  }

</script>

app/views/projects/_chart_filter_form.erb
<div class="row" id="costs-chart-form">
  <div class="mt-4 col-12">
    <form class="form" action="/projects/<%= @project.name %>/costs-breakdown" method="get" id="cost-chart-filter">
      <div class="form-row">
        <div class="col-md-3"></div>
        <div class="form-group col-md-2">
          <label for="dataset-list" class="charts-form-label">Datasets:</label>
          <select multiple class="form-control cost-datasets-select" name="datasets[]" id="dataset-list">
            <% @possible_datasets.each do |dataset| %>
              <% selected = @datasets && @datasets&.include?(dataset) %>
              <option
                value='<%=dataset%>'
                <%= 'selected' if selected %>
                data-already-selected=<%= selected %>
              >
              <%= dataset %>
              </option>
            <% end %>
          </select>  
        </div>
        <div class="form-group col-md-2">
          <label for="from-date" class="charts-form-label">From:</label>
          <input class="form-control cost-chart-date" type="date" id='start-date'
                 name='start_date'
                 min='<%= @min_date %>'
                 max='<%= @max_date %>'
                 <%= "value=#{@start_date}" %>>
        </div>
        <div class="form-group col-md-2">
          <label for="to-date" class="charts-form-label">To:</label>
          <input class="form-control cost-chart-date" type="date" id='end-date'
                 name="end_date"
                 min='<%= @min_date %>'
                 max='<%= @max_date %>'
                 <%= "value=#{@end_date}" %>>
        </div>
      </div>
      <input type="hidden" name="project" value=<%= @project.name %>>
      <div class="form-row">
        <div class="col-md-3"></div>
        <div class="form-group col-md-4">
          <input type="submit" value="Filter" class="btn btn-primary"
                 id="submit-chart-filter">
          <%= link_to "Clear all", project_costs_breakdown_path(@project), class: "btn btn-danger" %>
        </div>
      </div>
    </form>
  </div>
</div>

app/views/projects/_latest_change.erb
<div id="latest-change"
     data-value="<%= @project.time_of_latest_change.to_s %>"
     data-project="<%= @project.name %>">
</div>

app/views/projects/audit_logs.js.erb
<% audit_logs = escape_javascript(render 'partials/audit_logs', locals: {logs: @logs}) %>
$('<%= audit_logs %>').insertAfter($('.audit-row').last());
$('.tool-tip').tooltip();
<% if !@more %>
  $('#load-more-logs').addClass('d-none');
<% end %>